# Generated by Django 6.0.3 on 2026-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventregistration_order'),
        ('payments', '0002_remove_order_updated_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_cents', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('refunded', 'Refunded')], default='incomplete', max_length=15)),
                ('payment_method', models.CharField(choices=[('online', 'Stripe Online'), ('in_person', 'In Person at Event')], default='online', max_length=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
