# Generated by Django 6.0.3 on 2026-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='incomplete', max_length=15),
        ),
    ]
