# Generated by Django 6.0.3 on 2026-10-04 02:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_remove_event_downtime_due"),
        ("payments", "0004_alter_transaction_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        help_text="The code players enter. Not case-sensitive.", max_length=32, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Shown to players as the discount reason.", max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent Off"), ("flat", "Flat Amount Off")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "percent_off",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Percent off the ticket (1-100). Only for Percent Off promotions.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "amount_off_cents",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Amount off the ticket in cents. Only for Flat Amount Off promotions.",
                        null=True,
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to run until the promotion is manually deactivated.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Uncheck to shut this promotion off immediately."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to auto-generate a random code. Codes are not case-sensitive.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="Who this voucher is for and why (admin only).", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this voucher was redeemed. Clear this to make it usable again.",
                        null=True,
                    ),
                ),
                (
                    "used_by_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers_used",
                        to="events.eventregistration",
                    ),
                ),
            ],
        ),
    ]
