# Generated by Django 6.0.3 on 2026-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_promotion_voucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("canceled", "Canceled"),
                ],
                default="incomplete",
                max_length=15,
            ),
        ),
    ]
