# Generated by Django 6.0.3 on 2026-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_transaction_canceled_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="refunded_amount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
