# Generated by Django 6.0.3 on 2026-05-23 05:51

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('event_type', models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior'), ('feast', 'Feast'), ('other', 'Other')], default='other', max_length=10)),
                ('base_price_cents', models.IntegerField(help_text='Base price of a ticket for the event before discounts in cents.')),
                ('registration_available', models.BooleanField(default=True, help_text='Disables registration buttons if unchecked while allowing information for events to be shared.')),
                ('start_time', models.DateTimeField(default=events.models.default_start_time)),
                ('end_time', models.DateTimeField(default=events.models.default_end_time)),
                ('downtime_due', models.DateTimeField(default=events.models.default_downtime_due, help_text='This is the date by which attendees of the event must respond to the post event survey.')),
                ('event_image', models.ImageField(blank=True, upload_to=events.models.upload_event_main)),
                ('photographer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=events.models.upload_event_album)),
                ('alt_text', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='events.event')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='EventPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('min_age', models.PositiveSmallIntegerField(help_text='Lower Age Requirement for this tier.')),
                ('max_age', models.PositiveSmallIntegerField(help_text='Upper Age Requirement for this tier.')),
                ('price_cents', models.PositiveIntegerField(help_text='Base price in cents.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False)),
                ('arrival_time', models.DateTimeField(blank=True)),
                ('base_price_cents', models.PositiveIntegerField(help_text='Base price before discounts, in cents')),
                ('final_price_cents', models.PositiveIntegerField(help_text='Final price charged, in cents')),
                ('discounts', models.JSONField(blank=True, default=list)),
                ('additional_items', models.JSONField(blank=True, default=list)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='events.EventRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_registration'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'event_type'), name='unique_title_per_event_type'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('slug', 'event_type'), name='unique_slug_per_event_type'),
        ),
    ]
