# Generated by Django 5.1.3 on 2025-07-20 21:15

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='background_image',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text='The image that appears for this event in registration and event pages.', upload_to='images/Events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_available',
            field=models.BooleanField(default=True, help_text='Disables registration buttons if unchecked while allowing information for events to be shared.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='downtime_due',
            field=models.DateTimeField(default=events.models.default_downtime_due, help_text='This is the date by which attendees of the event must send a post event survey.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photographer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
