# Generated by Django 5.1.3 on 2025-11-25 20:42

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='downtime_due',
            field=models.DateTimeField(default=events.models.default_downtime_due, help_text='This is the date by which attendees of the event must respond to the post event survey.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='events.event'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(help_text='If linked to an event, defaults to "{Event Type} Post Event Survey: {Event Title}".', max_length=80),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='events.survey'),
        ),
    ]
