# Generated by Django 6.0.3 on 2026-05-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_manually_paid',
            field=models.BooleanField(default=False, help_text='Set to True if a Game Master manually accepts cash/check at the event without an online Order.'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The parent transaction cart used to clear this registration online.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='payments.order'),
        ),
    ]
