# Generated by Django 6.0.3 on 2026-06-10 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventregistration_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='is_manually_paid',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='declared_arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
