# Generated by Django 5.1.3 on 2025-09-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_background_image_event_event_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='EventPicture',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text='The image that appears for this event in registration and event pages. A default image is Hardcoded if none is provided.', upload_to='images/Events/'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(help_text='If left blank, will save as "<Event Type> Post Event Survey: <Event Title>" by default.', max_length=80),
        ),
    ]
