# Generated by Django 6.0.3 on 2026-06-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventregistration_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='order',
        ),
    ]
