# Generated by Django 5.1.3 on 2025-11-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_attendees_eventattendee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendees_new',
            new_name='attendees',
        ),
    ]
