# Generated by Django 5.1.3 on 2025-12-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_attendees_new_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('post_event', 'Post Event'), ('new_player', 'New Player'), ('other', 'Other')], default='post_event', max_length=20),
        ),
    ]
