# Generated by Django 6.0.3 on 2026-06-14 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventregistration_order'),
        ('payments', '0003_transaction_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='The parent transaction cart used to clear this registration online.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='payments.transaction'),
        ),
    ]
