# Generated by Django 6.0.3 on 2026-07-04 06:27

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventregistration_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='No event overview has been provided yet.', help_text='A short overview shown on the event detail and index pages.'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='No location has been provided yet.', help_text='The primary venue or gathering location for this event.', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='images/AoCEventBackgroundDefault.png', help_text='Primary banner shown on event pages when registration is open.', upload_to=events.models.upload_event_main),
        ),
    ]
