# Generated by Django 5.1.3 on 2025-12-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('general', 'General'), ('senior', 'Senior'), ('junior', 'Junior'), ('other', 'Other')], default='general', max_length=10),
        ),
    ]
