# Generated by Django 6.0.3 on 2026-07-08 22:07

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_description_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, help_text='Primary banner shown on event pages when registration is open.', null=True, upload_to=events.models.upload_event_main),
        ),
    ]
