# Generated by Django 5.1.3 on 2025-12-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
