# Generated by Django 6.0.3 on 2026-07-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='downtime_due',
        ),
    ]
