# Generated by Django 5.1.3 on 2025-12-30 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='amount_cents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='early_bird_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='first_time_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='late_arrival_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='student_discount',
            field=models.BooleanField(default=False),
        ),
    ]
