# Generated by Django 6.0.3 on 2026-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_settle_zero_dollar_registrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="refunded_cents",
            field=models.PositiveIntegerField(
                default=0, help_text="Amount refunded in Stripe for this registration, in cents."
            ),
        ),
    ]
