# Generated by Django 5.1.3 on 2026-01-08 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventattendee_amount_cents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='early_bird_discount',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='first_time_discount',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='late_arrival_discount',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='weapon_rental',
            field=models.BooleanField(default=False),
        ),
    ]
