# Generated by Django 5.1.3 on 2026-01-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_birthday_profile_date_of_birth_and_more'),
        ('events', '0010_remove_eventattendee_early_bird_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendee',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'profile')},
        ),
    ]
