# Generated by Django 5.1.3 on 2026-01-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_birthday_profile_date_of_birth_and_more'),
        ('events', '0011_rename_user_eventattendee_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='additional_items',
            field=models.JSONField(blank=True, default=list, help_text='Additional items charged snapshot'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='base_price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Base price before discounts, in cents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='discounts',
            field=models.JSONField(blank=True, default=list, help_text='Applied discounts snapshot'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='final_price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Final price charged, in cents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='events.EventAttendee', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior'), ('feast', 'Feast'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.profile'),
        ),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'profile'), name='unique_registration'),
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='registration_time',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='student_discount',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='weapon_rental',
        ),
    ]
