# Generated by Django 5.1.3 on 2026-01-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventattendee_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_price_cents',
            field=models.IntegerField(default=0, help_text='Base price of a ticket for the event before discounts in cents. I.E. 5000 would be equivalent to $50.\nWill be overrode if Price Tiers are provided.'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
                ('price_cents', models.PositiveIntegerField(help_text="Base price of a ticket for the provided age range in cents. Overrides the Event's Base Price.")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='events.event')),
            ],
        ),
    ]
