# Generated by Django 5.1.3 on 2026-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_base_price_cents_eventpricetier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='base_price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Base price before discounts, in cents'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='final_price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Final price charged, in cents'),
        ),
    ]
