# Generated by Django 5.1.3 on 2026-01-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventattendee_base_price_cents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='amount_cents',
        ),
    ]
