# Generated by Django 5.1.3 on 2026-01-21 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_eventattendee_amount_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
