# Generated by Django 5.1.3 on 2026-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventattendee_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='base_price_cents',
            field=models.PositiveIntegerField(help_text='Base price before discounts, in cents'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='final_price_cents',
            field=models.PositiveIntegerField(help_text='Final price charged, in cents'),
        ),
    ]
