# Generated by Django 5.1.3 on 2026-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventattendee_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='base_price_cents',
            field=models.IntegerField(help_text='Base price of a ticket for the event before discounts in cents\nI.E. 5000 would be equivalent to $50.\nWill be overrode if Price Tiers are provided.'),
        ),
    ]
