# Generated by Django 5.1.3 on 2026-01-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_base_price_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='base_price_cents',
            field=models.IntegerField(help_text='Base price of a ticket for the event before discounts in cents.\nI.E. 5000 would be equivalent to $50.\nWill be overrode if Price Tiers are provided.'),
        ),
        migrations.AlterField(
            model_name='eventpricetier',
            name='max_age',
            field=models.PositiveSmallIntegerField(help_text='Upper Age Requirement for this tier.'),
        ),
        migrations.AlterField(
            model_name='eventpricetier',
            name='min_age',
            field=models.PositiveSmallIntegerField(help_text='Lower Age Requirement for this tier.'),
        ),
    ]
