# Generated by Django 5.1.3 on 2026-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_base_price_cents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='base_price_cents',
            field=models.IntegerField(help_text='Base price of a ticket for the event before discounts in cents.\nI.E. 5000 would be equivalent to $50.\nServes as a fallback if price tiers are provided that is used if a user does not fall into any age bracket.'),
        ),
    ]
