services:
  db:
    image: postgres:16-alpine
    container_name: aoc_db
    restart: always
    volumes:
      - aoc_data:/var/lib/postgresql/data/
    networks:
      - aoc_net
    env_file:
      - .env

  webapp:
    container_name: aoc_webapp
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --noinput &&
             gunicorn ageofclaritas.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - aoc_static:/var/www/static/aoc
      - aoc_media:/var/www/media/aoc
    restart: always
    networks:
      - aoc_net
      - web_gateway
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - aoc_static:/var/www/static/aoc:ro
      - aoc_media:/var/www/media/aoc:ro
    networks:
      - aoc_net
      - web_gateway
    depends_on:
      - webapp

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - aoc_net
    depends_on:
      - nginx

volumes:
  aoc_data:
  aoc_static:
  aoc_media:

networks:
  aoc_net:
    driver: bridge
  web_gateway:
    external: true
