services:
  db:
    container_name: kasenfudge_db
    image: postgres:16-alpine
    restart: always
    volumes:
      - kasenfudge_data:/var/lib/postgresql/data/
    networks:
      - kasenfudge_net
    env_file:
      - .env

  webapp:
    container_name: kasenfudge_webapp
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn ageofclaritas.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - kasenfudge_static:/var/www/static/aoc
      - kasenfudge_media:/var/www/media/aoc
    restart: always
    networks:
      - kasenfudge_net
      - web_gateway
    env_file:
      - .env
    depends_on:
      - db

volumes:
  kasenfudge_data:
    name: kasenfudge_data
  kasenfudge_static:
    name: kasenfudge_static
  kasenfudge_media:
    name: kasenfudge_media

networks:
  kasenfudge_net:
    driver: bridge
  web_gateway:
    external: true