services:
  db:
    container_name: ageofclaritas_db
    image: postgres:16-alpine
    restart: always
    volumes:
      - ageofclaritas_data:/var/lib/postgresql/data/
    networks:
      - ageofclaritas_net
    env_file:
      - .env

  webapp:
    container_name: ageofclaritas_webapp
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn ageofclaritas.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ageofclaritas_static:/var/www/static/aoc
      - ageofclaritas_media:/var/www/media/aoc
    restart: always
    networks:
      - ageofclaritas_net
      - web_gateway
    env_file:
      - .env
    depends_on:
      - db

volumes:
  ageofclaritas_data:
    name: ageofclaritas_data
  ageofclaritas_static:
    name: ageofclaritas_static
  ageofclaritas_media:
    name: ageofclaritas_media

networks:
  ageofclaritas_net:
    driver: bridge
  web_gateway:
    external: true