# Generated by Django 6.0.3 on 2026-07-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quote', models.TextField()),
                ('role', models.CharField(blank=True, default='', help_text="Optional context shown under the name, e.g. a character name or 'Attended 3 events'.", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the carousel without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the carousel.')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
