# Generated by Django 6.0.3 on 2026-07-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='images/Team/')),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
