# Generated by Django 5.1.3 on 2025-07-03 01:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('effective_date', models.DateField(auto_now=True, help_text='Will update automatically when the waiver is created or updated.')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Only one waiver should be active at a time.')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WaiverSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.waiver')),
            ],
            options={
                'unique_together': {('user', 'waiver')},
            },
        ),
    ]
