# Generated by Django 6.0.3 on 2026-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_status_expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
