# Generated by Django 5.1.3 on 2025-07-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_waiver_profile_birthday_profile_is_minor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiver',
            name='effective_date',
            field=models.DateField(auto_now_add=True, help_text='Will update automatically when the waiver is created or updated.'),
        ),
    ]
