# Generated by Django 6.0.3 on 2026-05-25 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='Links this profile to a primary adult guardian account. Enables unified family checkouts and minor event registration management.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
