# Generated by Django 6.0.3 on 2026-07-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_parent_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_veteran',
            field=models.BooleanField(default=False, help_text='Designates whether this player attended LARP events prior to the new site.'),
        ),
    ]
