# Generated by Django 5.1.3 on 2025-07-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_waiver_effective_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiver',
            options={'ordering': ['-effective_date']},
        ),
    ]
