# Generated by Django 6.0.3 on 2026-07-29 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_veteran'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_guardian',
            field=models.ForeignKey(blank=True, help_text="An adult account has requested to link as this user's guardian; awaiting approval.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_dependents', to=settings.AUTH_USER_MODEL),
        ),
    ]
