# Generated by Django 5.1.3 on 2026-01-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_minor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_new_player',
        ),
    ]
