server {
    listen 80;
    server_name kasenfudge.me www.kasenfudge.me cis598.kasenfudge.me;

    # Certbot challenge location (keep this for future renewals)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kasenfudge.me www.kasenfudge.me;

    client_max_body_size 20M;

    # SSL Certificates
    ssl_certificate /etc/letsencrypt/live/kasenfudge.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kasenfudge.me/privkey.pem;

    # Security Optimizations
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://aoc_webapp:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /var/www/static/aoc/;
    }

    location /media/ {
        alias /var/www/media/aoc/;
    }
}

server {
    listen 443 ssl;
    server_name cis598.kasenfudge.me;

    ssl_certificate /etc/letsencrypt/live/kasenfudge.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kasenfudge.me/privkey.pem;

    location / {
        # This NAME must match the container name in your OTHER docker-compose.yml
        proxy_pass http://cis598_webapp:8000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /var/www/static/cis598/;
    }
}