# Generated by Django 6.0.3 on 2026-07-21 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Defaults to two weeks after the linked event ends (or two weeks from today if no event is linked), at 11:59:59 PM.', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('downtime', 'Downtime'), ('new_player', 'New Player'), ('other', 'Other')], default='feedback', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(blank=True, help_text='If linked to an event, defaults to "{Survey Type} Survey for {Event Title}".', max_length=80),
        ),
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_surveys', through='surveys.SurveyAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='surveyassignment',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='uq_survey_assignment_once'),
        ),
    ]
