# Generated by Django 6.0.3 on 2026-07-27 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_downtime_due'),
        ('surveys', '0002_survey_due_date_alter_survey_survey_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('downtime', 'Downtime'), ('new_player', 'New Player'), ('ludus', 'Ludus'), ('other', 'Other')], default='feedback', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('survey_type', 'event'), name='uq_one_survey_type_per_event'),
        ),
    ]
