"""
Django settings for ageofclaritas project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv

# ==========================================
# Paths & Environment Loader
# ==========================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the project runtime environment profile mapping
load_dotenv(BASE_DIR / ".env", override=True)


# ==========================================
# Security & Deployment Guardrails
# ==========================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG") == "True" else False

ALLOWED_HOSTS = json.loads(os.getenv("ALLOWED_HOSTS", '["127.0.0.1", "localhost"]'))


# ==========================================
# Reverse Proxy & SSL Handshakes
# ==========================================
# Tells Django to intercept upstream HTTPS validation through the Nginx container proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = False  # Enforced directly by Nginx server blocks
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    "https://kasenfudge.me",  # Staging Verification Endpoint
    "https://www.kasenfudge.me",  # Staging Canonical www Routing
    "https://ageofclaritas.com",  # Production Root Domain
    "https://www.ageofclaritas.com",  # Production Canonical www Routing
]


# ==========================================
# Application Architecture & Authentication
# ==========================================
# Use the custom domain identity engine instead of standard Django records
# Docs: https://docs.djangoproject.com/en/6.0/topics/auth/customizing/#specifying-a-custom-user-model
AUTH_USER_MODEL = "accounts.CustomUser"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-Party Dependencies
    "django_summernote",  # Integrated rich-text rendering engine
    # Age of Claritas Core Modules
    "ageofclaritas",  # Structural configuration root
    "core.apps.CoreConfig",  # Public portal landing surfaces
    "accounts.apps.AccountsConfig",  # Profile & ledger orchestration
    "rulebook.apps.RulebookConfig",  # Mechanical game documentation
    "events.apps.EventsConfig",  # Event mapping & registrations
    "surveys.apps.SurveysConfig",  # Player analytical surveying
    "payments.apps.PaymentsConfig",  # Stripe financial transactional gateway
]

# Redirect internal third-party engine schemas away from read-only application folders
MIGRATION_MODULES = {
    "django_summernote": None,
}


# ==========================================
# Request / Response Pipeline Middleware
# ==========================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # High-efficiency file caching
]

ROOT_URLCONF = "ageofclaritas.urls"

WSGI_APPLICATION = "ageofclaritas.wsgi.application"


# ==========================================
# Interface Render Layout Templates
# ==========================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # DIRS only needs folders that sit OUTSIDE of your local apps, of which we have none.
        "DIRS": [BASE_DIR / "templates"],
        # APP_DIRS=True tells Django to auto-discover "app_name/templates/" automatically
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ==========================================
# Persistent Relational Database Cluster
# ==========================================
# Docs: https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# ==========================================
# Password Hashing Validation Profiles
# ==========================================
# Docs: https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==========================================
# Regionalization & Time Zone Vectors
# ==========================================
# Docs: https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Chicago"
USE_I18N = True
USE_TZ = True


# ==========================================
# Asset Storage & Serving Infrastructure
# ==========================================
# Docs: https://docs.djangoproject.com/en/6.0/howto/static-files/
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", "/var/www/static/aoc")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", "/var/www/media/aoc")

# Production static delivery wrapper (Intercepts fallback delivery if Nginx drops asset threads)
# Docs: https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ==========================================
# Identity Redirection Targets
# ==========================================
# Docs: https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "core:index"
LOGOUT_REDIRECT_URL = "core:index"


# ==========================================
# Stripe API Financial Integration
# ==========================================
# Docs: https://docs.stripe.com/api
# Elements: https://docs.stripe.com/payments/accept-a-payment?platform=web&ui=elements
STRIPE_PUBLISHABLE_KEY = os.environ["STRIPE_PUBLISHABLE_KEY"]
STRIPE_SECRET_KEY = os.environ["STRIPE_SECRET_KEY"]
STRIPE_WEBHOOK_SECRET = os.environ["STRIPE_WEBHOOK_SECRET"]
