# Generated by Django 6.0.3 on 2026-05-15 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Kin',
                'verbose_name_plural': 'Kin',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('class_type', models.CharField(choices=[('base', 'Base Class'), ('faction', 'Faction'), ('elemental', 'Elemental'), ('manifold', 'Manifold')], default='base', max_length=15)),
                ('has_special_rules', models.BooleanField(default=False)),
                ('special_rules', models.TextField(blank=True, null=True)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='rulebook.class')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('can_start_with', models.BooleanField(default=True)),
                ('kin_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulebook.kin')),
            ],
        ),
        migrations.CreateModel(
            name='Kin_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/Kin/')),
                ('kin_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulebook.kin')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_rankless', models.BooleanField(default=False)),
                ('talent_type', models.CharField(choices=[('skill', 'Skill'), ('ability', 'Ability'), ('weapon', 'Weapon Title'), ('armor', 'Armor Title'), ('support', 'Support Title'), ('misc', 'Misc. Title'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], default='ability', max_length=15)),
                ('class_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.class')),
            ],
        ),
    ]
