# Generated by Django 5.1.1 on 2024-10-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_name', models.CharField(max_length=50)),
                ('talent_description', models.CharField()),
                ('talent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulebook.class')),
            ],
        ),
    ]
