# Generated by Django 6.0.3 on 2026-05-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='kin',
            options={'ordering': ['name'], 'verbose_name': 'Kin', 'verbose_name_plural': 'Kin'},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='kin',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='kin_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='rulebook.kin'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[(None, 'Choose a Class Type...'), ('guild', 'Guild'), ('faction', 'Faction'), ('elemental', 'Elemental'), ('manifold', 'Manifold'), ('classless', 'Classless')], max_length=15),
        ),
        migrations.AlterField(
            model_name='kin_image',
            name='kin_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kin_images', to='rulebook.kin'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('name', 'kin_for')},
        ),
    ]
