# Generated by Django 5.1.1 on 2024-11-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='is_rankless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_rank1',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_rank2',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_rank3',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_rankless',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='talent',
            name='talent_name',
            field=models.CharField(max_length=40),
        ),
    ]
