# Generated by Django 5.1.3 on 2024-11-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0002_talent_is_rankless_talent_talent_rank1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField()),
                ('size', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_class',
            new_name='class_for',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_rank1',
            new_name='rank1_effect',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_rank2',
            new_name='rank2_effect',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_rank3',
            new_name='rank3_effect',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='talent_rankless',
            new_name='rankless_effect',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField()),
                ('kin_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulebook.kin')),
            ],
        ),
        migrations.CreateModel(
            name='Kin_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('kin_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulebook.kin')),
            ],
        ),
    ]
