# Generated by Django 6.0.3 on 2026-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0002_alter_attribute_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': [models.Case(models.When(talent_type='skill', then=0), models.When(talent_type='ability', then=1), models.When(talent_type='weapon', then=2), models.When(talent_type='armor', then=3), models.When(talent_type='support', then=4), models.When(talent_type='misc', then=5), models.When(talent_type='tier_1', then=6), models.When(talent_type='tier_2', then=7), models.When(talent_type='tier_3', then=8), output_field=models.IntegerField()), 'priority', 'name']},
        ),
        migrations.RemoveField(
            model_name='class',
            name='has_special_rules',
        ),
    ]
