# Generated by Django 5.1.3 on 2024-11-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0003_kin_rename_class_description_class_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='type_of',
            field=models.CharField(choices=[('skill', 'SKILL'), ('ability', 'ABILITY'), ('warrior title', 'WARRIOR_TITLE'), ('tier 1', 'TIER_1'), ('tier 2', 'TIER_2'), ('tier 3', 'TIER_3')], default='ability', max_length=15),
        ),
    ]
