# Generated by Django 5.1.3 on 2024-11-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0004_talent_type_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='type_of',
            new_name='talent_type',
        ),
    ]
