# Generated by Django 5.1.3 on 2024-11-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0005_rename_type_of_talent_talent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(default='4guysHouseOctavious.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='kin',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(),
        ),
    ]
