# Generated by Django 6.0.3 on 2026-07-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0006_make_slugs_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
