# Generated by Django 5.1.3 on 2024-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0006_definition_class_image_alter_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(default='4guysHouseOctavious.jpg', upload_to='static/rulebook/images/'),
        ),
    ]
