# Generated by Django 6.0.3 on 2026-07-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0006_make_slugs_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='term',
            new_name='name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
