# Generated by Django 6.0.3 on 2026-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0007_attribute_priority_alter_definition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='index_type',
            field=models.CharField(choices=[('class', 'Class'), ('talent', 'Talent'), ('kin', 'Kin'), ('attribute', 'Attribute'), ('glossary', 'Glossary Term')], default='glossary', max_length=15),
        ),
    ]
