# Generated by Django 5.1.3 on 2024-11-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0007_alter_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(default='static/rulebook/images/4guysHouseOctavious.jpg', upload_to='static/rulebook/images/'),
        ),
    ]
