# Generated by Django 6.0.3 on 2026-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0008_alter_definition_index_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='definition',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='definition',
            name='index_type',
            field=models.CharField(choices=[('class', 'Class'), ('talent', 'Talent'), ('kin', 'Kin'), ('attribute', 'Attribute'), ('glossary', 'Glossary Term'), ('experience_denomination', 'Experience Denomination'), ('currency_denomination', 'Currency Denomination'), ('weapon_dexterity', 'Weapon Dexterity'), ('shield', 'Shield'), ('tome', 'Tome'), ('equipment_crafting', 'Equipment Crafting'), ('magical_crafting', 'Magical Crafting'), ('potion_crafting', 'Potion Crafting'), ('utilization_tag', 'Utilization Tag'), ('frequency', 'Frequency')], default='glossary', max_length=30),
        ),
        migrations.AlterField(
            model_name='definition',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.RemoveField(
            model_name='definition',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='source_id',
        ),
    ]
