# Generated by Django 5.1.3 on 2024-11-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0008_alter_class_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='class_for',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='kin_image',
            name='image',
            field=models.ImageField(default='static/rulebook/images/4guysHouseOctavious.jpg', upload_to='static/rulebook/images/'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='rank1_effect',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talent',
            name='rank2_effect',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talent',
            name='rank3_effect',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talent',
            name='rankless_effect',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('class_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulebook.class')),
            ],
        ),
        migrations.AddField(
            model_name='talent',
            name='faction_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.faction'),
        ),
    ]
