# Generated by Django 6.0.3 on 2026-08-19 00:52

from django.db import migrations, models

# Legacy rows synced under the (now-removed) slug-keyed scheme all have
# source_id NULL as of the AlterField below, and their slug is exactly
# "<index_type>-<source's own slug>" -- the same convention build_slug()
# still uses. Backfilling source_id from that lets the post-migration state
# match what the mirrored rows would look like if they'd been created under
# the source_id-keyed scheme from the start, instead of leaving them NULL
# (which would make reindex_definitions read them as stale, and make
# signals.sync_index create a colliding duplicate on the next source save).
MIRRORED_MODELS = ["class", "talent", "kin", "attribute"]


def backfill_source_ids(apps, schema_editor):
    Definition = apps.get_model("rulebook", "Definition")

    for index_type in MIRRORED_MODELS:
        source_model = apps.get_model("rulebook", index_type)
        slug_to_pk = dict(source_model.objects.values_list("slug", "pk"))

        for definition in Definition.objects.filter(index_type=index_type, source_id__isnull=True):
            prefix = f"{index_type}-"
            if not definition.slug.startswith(prefix):
                continue
            pk = slug_to_pk.get(definition.slug[len(prefix):])
            if pk is not None:
                definition.source_id = pk
                definition.save(update_fields=["source_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0008_alter_definition_index_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='definition',
            name='index_type',
            field=models.CharField(choices=[('class', 'Class'), ('talent', 'Talent'), ('kin', 'Kin'), ('attribute', 'Attribute'), ('glossary', 'Glossary Term'), ('experience_denomination', 'Experience Denomination'), ('currency_denomination', 'Currency Denomination'), ('weapon_dexterity', 'Weapon Dexterity'), ('shield', 'Shield'), ('tome', 'Tome'), ('equipment_crafting', 'Equipment Crafting'), ('magical_crafting', 'Magical Crafting'), ('potion_crafting', 'Potion Crafting'), ('utilization_tag', 'Utilization Tag'), ('frequency', 'Frequency')], default='glossary', max_length=30),
        ),
        migrations.AlterField(
            model_name='definition',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the source row when this Definition is synced from another model. Null for hand-authored entries.', null=True),
        ),
        migrations.RunPython(backfill_source_ids, migrations.RunPython.noop),
    ]
