# Generated by Django 5.1.3 on 2024-11-28 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0009_remove_talent_class_for_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='faction_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rulebook.class'),
        ),
        migrations.DeleteModel(
            name='Faction',
        ),
    ]
