# Generated by Django 6.0.3 on 2026-08-19 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0009_remove_definition_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulepage',
            options={'ordering': ['priority', 'title']},
        ),
        migrations.AddField(
            model_name='rulepage',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.'),
        ),
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, default='', help_text='CKEditor HTML content.')),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rulebook.rulepage')),
            ],
            options={
                'ordering': ['priority', 'title'],
                'unique_together': {('page', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RuleSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, default='', help_text='CKEditor HTML content.')),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers float to the top (e.g., 0, 1, 2). Default is 100.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='rulebook.rulesection')),
            ],
            options={
                'ordering': ['priority', 'title'],
                'unique_together': {('section', 'slug')},
            },
        ),
    ]
