# Generated by Django 5.1.3 on 2024-11-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0010_alter_talent_faction_for_delete_faction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
        migrations.RemoveField(
            model_name='class',
            name='image',
        ),
    ]
