# Generated by Django 6.0.3 on 2026-08-20 17:05

from django.db import migrations, models

# The removed choices below (experience_denomination, currency_denomination,
# weapon_dexterity, shield, tome, equipment_crafting, magical_crafting,
# potion_crafting, utilization_tag, frequency) never had DB-level enforcement
# -- Django CharField choices are validation-only -- so a bare AlterField here
# can't actually fail on old data. This step exists anyway as a real cleanup:
# any hand-authored (source_id IS NULL) Definition row still carrying one of
# the retired sub-types gets folded back into the single GLOSSARY catch-all,
# so nothing is left holding a value that's no longer a declared choice.
VALID_INDEX_TYPES = {"class", "talent", "kin", "attribute", "glossary"}


def collapse_retired_types_to_glossary(apps, schema_editor):
    Definition = apps.get_model("rulebook", "Definition")
    (
        Definition.objects.filter(source_id__isnull=True)
        .exclude(index_type__in=VALID_INDEX_TYPES)
        .update(index_type="glossary")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0010_alter_rulepage_options_rulepage_priority_rulesection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="tag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short label shown as a badge next to the term on the Glossary page. For Class/Talent/Kin/Attribute rows this is auto-filled with the Index Type's label the first time it's blank, but never overwritten once set by hand -- edit freely.",
                max_length=50,
            ),
        ),
        migrations.RunPython(collapse_retired_types_to_glossary, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="definition",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("class", "Class"),
                    ("talent", "Talent"),
                    ("kin", "Kin"),
                    ("attribute", "Attribute"),
                    ("glossary", "Glossary"),
                ],
                default="glossary",
                max_length=30,
            ),
        ),
    ]
