# Generated by Django 5.1.3 on 2024-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0011_remove_class_description_remove_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.CharField(blank=True, default=''),
        ),
    ]
