# Generated by Django 6.0.3 on 2026-08-20 22:00

from django.db import migrations, models
from django.db.models import Value
from django.db.models.functions import Concat

# RuleSection/RuleSubsection.slug used to be stored bare (e.g. "combat-basics"),
# with "section-"/"subsection-" prepended only at template-render time to build
# the real HTML anchor id. That's now baked into the slug itself (see
# RuleSection.build_slug/RuleSubsection.build_slug), so existing rows -- whose
# stored slug is already exactly slugify(title) -- just need the constant
# prefix prepended once. Guarded with exclude(slug__startswith=...) so this is
# safe to re-run (idempotent) if a deploy ever retries it.


def prefix_existing_slugs(apps, schema_editor):
    RuleSection = apps.get_model("rulebook", "RuleSection")
    RuleSubsection = apps.get_model("rulebook", "RuleSubsection")
    RuleSection.objects.exclude(slug__startswith="section-").update(slug=Concat(Value("section-"), "slug"))
    RuleSubsection.objects.exclude(slug__startswith="subsection-").update(
        slug=Concat(Value("subsection-"), "slug")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0011_definition_tag_alter_definition_index_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesection',
            name='slug',
            field=models.SlugField(blank=True, max_length=115),
        ),
        migrations.AlterField(
            model_name='rulesubsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=115),
        ),
        migrations.RunPython(prefix_existing_slugs, migrations.RunPython.noop),
    ]
