# Generated by Django 6.0.3 on 2026-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0012_alter_rulesection_slug_alter_rulesubsection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='glossary_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='definition',
            name='target_url',
            field=models.CharField(blank=True, default='', help_text='Optional link. If set, the term on the Glossary page links to this URL.', max_length=255),
        ),
    ]
