# Generated by Django 5.1.3 on 2024-11-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0012_alter_talent_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='faction_for',
            new_name='class_for',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='rank1_effect',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='rank2_effect',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='rank3_effect',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='rankless_effect',
        ),
    ]
