# Generated by Django 6.0.3 on 2026-09-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulebook", "0012_alter_rulesection_slug_alter_rulesubsection_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="target_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Page that this term should link to when clicked in the Glossary.",
                max_length=255,
            ),
        ),
    ]
