# Generated by Django 5.1.3 on 2024-11-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0013_rename_faction_for_talent_class_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='talent_type',
            field=models.CharField(choices=[('skill', 'SKILL'), ('ability', 'ABILITY'), ('weapon', 'WEAPON_WARRIOR_TITLE'), ('armor', 'ARMOR_WARRIOR_TITLE'), ('support', 'SUPPORT_WARRIOR_TITLE'), ('other', 'OTHER_WARRIOR_TITLE'), ('tier 1', 'TIER_1'), ('tier 2', 'TIER_2'), ('tier 3', 'TIER_3')], default='ability', max_length=15),
        ),
    ]
