# Generated by Django 5.1.3 on 2024-12-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0014_alter_talent_talent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subclasses',
            field=models.ManyToManyField(blank=True, related_name='parent_classes', to='rulebook.class'),
        ),
        migrations.AlterField(
            model_name='kin_image',
            name='image',
            field=models.ImageField(default='static/images/4guysHouseOctavious.jpg', upload_to='images/'),
        ),
    ]
