# Generated by Django 5.1.3 on 2024-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0015_class_subclasses_alter_kin_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.TextField(),
        ),
    ]
