# Generated by Django 5.1.3 on 2024-12-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0016_alter_attribute_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kin',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
