# Generated by Django 5.1.3 on 2024-12-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0017_alter_definition_description_alter_kin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='talent_type',
            field=models.CharField(choices=[('skill', 'SKILL'), ('ability', 'ABILITY'), ('weapon', 'WEAPON_WARRIOR_TITLE'), ('armor', 'ARMOR_WARRIOR_TITLE'), ('support', 'SUPPORT_WARRIOR_TITLE'), ('other', 'OTHER_WARRIOR_TITLE'), ('tier_1', 'TIER_1'), ('tier_2', 'TIER_2'), ('tier_3', 'TIER_3')], default='ability', max_length=15),
        ),
    ]
