# Generated by Django 5.1.3 on 2024-12-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0018_alter_talent_talent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kin',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kin',
            name='size',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kin_image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/Kin/'),
        ),
    ]
