# Generated by Django 5.1.3 on 2024-12-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0019_kin_short_description_alter_kin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kin',
            name='size',
            field=models.CharField(blank=True, default=''),
        ),
    ]
