# Generated by Django 5.1.3 on 2024-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0020_alter_kin_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='can_start_with',
            field=models.BooleanField(default=False),
        ),
    ]
