# Generated by Django 5.1.3 on 2024-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0021_attribute_can_start_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='can_start_with',
            field=models.BooleanField(default=True),
        ),
    ]
