# Generated by Django 5.1.3 on 2025-02-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0022_alter_attribute_can_start_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='talent_type',
            field=models.CharField(choices=[('skill', 'SKILL'), ('ability', 'ABILITY'), ('weapon', 'WEAPON_WARRIOR_TITLE'), ('armor', 'ARMOR_WARRIOR_TITLE'), ('support', 'SUPPORT_WARRIOR_TITLE'), ('miscellaneous', 'MISCELLANEOUS_WARRIOR_TITLE'), ('tier_1', 'TIER_1'), ('tier_2', 'TIER_2'), ('tier_3', 'TIER_3')], default='ability', max_length=15),
        ),
    ]
