# Generated by Django 5.1.3 on 2025-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0024_alter_talent_talent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subclasses',
        ),
        migrations.AddField(
            model_name='class',
            name='factions',
            field=models.ManyToManyField(blank=True, related_name='base_classes', to='rulebook.class'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='talent_type',
            field=models.CharField(choices=[('skill', 'Skill'), ('ability', 'Ability'), ('weapon', 'Weapon Title'), ('armor', 'Armor Title'), ('support', 'Support Title'), ('misc', 'Misc. Title'), ('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], default='ability', max_length=15),
        ),
    ]
