# Generated by Django 5.1.3 on 2025-05-27 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0025_remove_class_subclasses_class_factions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='factions',
        ),
        migrations.AddField(
            model_name='class',
            name='base_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='rulebook.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='has_special_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='special_rules',
            field=models.CharField(default=None, null=True),
        ),
    ]
