# Generated by Django 5.1.3 on 2025-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0026_remove_class_factions_class_base_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='special_rules',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
