# Generated by Django 5.1.3 on 2025-07-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0027_alter_class_special_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='special_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kin',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kin',
            name='size',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
