# Generated by Django 5.1.3 on 2025-07-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0028_alter_attribute_name_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='kin',
            options={'verbose_name': 'Kin', 'verbose_name_plural': 'Kin'},
        ),
    ]
