# Generated by Django 5.1.3 on 2025-07-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0029_alter_class_options_alter_kin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='base_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='rulebook.class'),
        ),
    ]
