# Generated by Django 5.1.3 on 2025-09-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0030_alter_class_base_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='base_class',
            new_name='guild',
        ),
        migrations.AddField(
            model_name='class',
            name='is_base_class',
            field=models.BooleanField(default=False),
        ),
    ]
