# Generated by Django 5.1.3 on 2025-09-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebook', '0031_rename_base_class_class_guild_class_is_base_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='is_base_class',
        ),
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('base', 'Base Class'), ('faction', 'Faction'), ('elemental', 'Elemental'), ('manifold', 'Manifold')], default='base', max_length=15),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='kin',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
